/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/add/Add.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    FriendShip: typeof import('./src/components/friend/FriendShip.vue')['default']
    Headline: typeof import('./src/components/Headline.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    MyWork: typeof import('./src/components/mywork/MyWork.vue')['default']
    Pin: typeof import('./src/components/detail/Pin.vue')['default']
    PinMasonry: typeof import('./src/components/PinMasonry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./src/components/Searchbar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Signup: typeof import('./src/components/login/Signup.vue')['default']
    WaterfallGrid: typeof import('./src/components/WaterfallGrid.vue')['default']
    WaterfallGrid2: typeof import('./src/components/WaterfallGrid.vue')['default']
  }
}
